[versions]
libraryVersion = "1.1.0-alpha03"
androidTargetSdk = "36"
androidMinSdk = "21"
javaSdk = "11"
vGradle = "8.12.3"
vKotlin = "2.2.21"
vKotlinSerialization = "1.9.0"
vCoroutines = "1.10.2"
vMavenPublish = "0.35.0"
vKtor = "3.3.2"

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "vKotlin" }
kotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "vGradle" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "vKotlin" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vMavenPublish" }

[libraries]
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "vKotlinSerialization" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "vCoroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "vCoroutines" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "vKtor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "vKtor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "vKtor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "vKtor" }
ktor-client-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "vKtor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "vKtor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "vKtor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "vKtor" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "vKotlin" }
