name: Pull Request Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Test
        run: ./gradlew jvmTest
      - name: Send Build Alert
        run: ./gradlew :sample:run --args="--build"
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}
